# Generated by Django 4.2.7 on 2023-11-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_nm', models.TextField()),
                ('cur_unit', models.TextField()),
                ('deal_bas_r', models.FloatField()),
                ('kftc_bkpr', models.FloatField()),
                ('kftc_deal_bas_r', models.FloatField()),
                ('ten_dd_efee_r', models.IntegerField()),
                ('ttb', models.FloatField()),
                ('tts', models.FloatField()),
                ('yy_efee_r', models.IntegerField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
